
TARGET = aesdsocket
OBJS = aesdsocket.c

all: $(OBJS)
	$(CROSS_COMPILE)gcc $(OBJS) -o $(TARGET)


default: $(OBJS)
	$(CROSS_COMPILE)gcc $(OBJS) -o $(TARGET)

clean:
	rm -f *.o aesdsocket

