
all: $(OBJS)
#all: writer.c
	$(CC) $(CFLAGS) $(INCLUDES) $(OBJS) -o $(TARGET) $(LDFLAGS)
#$(CROSS_COMPILE)gcc -g -Wall writer.c -o writer
# $(CROSS_COMPILE)$(CC) -g -Wall writer.c -o writer
#file writer.o > ../assignments/assignment2/fileresult.txt

clean:
	rm -f *.o writer

